name: GitHub Profile Summary Cards

on:
  schedule:
    # Daily at 04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "profile-summary-card-output/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/profile-summary-cards@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Ismael-Sallami
